sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root123
  alioss:
    endpoint: XXX
    access-key-id: XXX
    access-key-secret: XXX
    bucket-name: XXX
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: XXX
    secret: XXX