sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root123
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t5iqYZjZzT3iSPznSyt
    access-key-secret: 4bul2QgNlmGHZb3BAkGaGVlTY06Z4F
    bucket-name: tlias-lxq
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10